[package]
name = "registration_system_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sqlx = { version = "0.6", features = ["mysql", "runtime-actix-native-tls"] }
dotenv = "0.15"
